version: "3"
services:
  db:
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: "12345"
    ports:
      - "3333:3306"
    volumes:
      - ./dump:/docker-entrypoint-initdb.d
  tst:
    image: test
    depends_on:
      - "db"
    ports:
      - "8800:8888"
    volumes:
      - ./data:/var/lib/mysql